map f5 launch --location=hsplit
map f6 launch --location=vsplit
map f4 launch --location=split
map f7 layout_action rotate

map alt+n launch --location=split --cwd=current

map alt+w>shift+up move_window up
map alt+w>shift+down move_window down
map alt+w>shift+left move_window left
map alt+w>shift+right move_window right

map alt+w>ctrl+shift+up layout_action move_to_screen_edge top
map alt+w>ctrl+shift+left layout_action move_to_screen_edge left 
map alt+w>ctrl+shift+right layout_action move_to_screen_edge right 
map alt+w>ctrl+shift+down layout_action move_to_screen_edge bottom
map alt+w>n set_window_title
map alt+w>q close_window

map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down

map alt+ctrl+n new_tab
map alt+ctrl+left previous_tab
map alt+ctrl+right next_tab
map alt+t>n set_tab_title
map alt+t>s select_tab
map alt+t>q close_tab
